companies_list = ['University of Virginia', 'Paylocity', 'Texas Tech University', 'Boston University',
                  'University of Connecticut',
                  'Arizona State University', 'Georgia Tech', 'UC Davis', 'lululemon', 'University of Pennsylvania',
                  'NYU (New York University)', 'Texas A&M University', 'In-N-Out Burger', 'Duke University',
                  'Stanford University',
                  'Google', 'Michigan State University', "Trader Joe's", 'Emory University', 'Genentech', 'UC San Diego',
                  'University of South Florida', 'Mentor Graphics', 'Mastech Digital', 'University of Washington',
                  'University of Southern California', 'MD Anderson Cancer Center', 'Stryker', "Trader Joe's",
                  'UC San Diego', 'Emory University', 'Genentech', 'University of Southern California',
                  'University of Washington',
                  'Fast Enterprises', 'Penn State', 'Morrison Healthcare']
