# Generated by Django 3.1.6 on 2021-02-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassdoorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30, null=True)),
                ('companyDesc', models.TextField(null=True)),
                ('companyJobs', models.CharField(max_length=10, null=True)),
                ('companyInterviews', models.CharField(max_length=10, null=True)),
                ('companyBenefits', models.CharField(max_length=10, null=True)),
                ('overallRating', models.CharField(max_length=10, null=True)),
                ('totalReviews', models.CharField(max_length=10, null=True)),
                ('recommendToFriend', models.CharField(max_length=10, null=True)),
                ('approveOfCEO', models.CharField(max_length=10, null=True)),
                ('overallPros', models.TextField(null=True)),
                ('overallCons', models.TextField(null=True)),
                ('reviewHeadings', models.TextField(null=True)),
                ('reviewDescriptions', models.TextField(null=True)),
                ('reviewPros', models.TextField(null=True)),
                ('reviewCons', models.TextField(null=True)),
                ('reviewDate', models.TextField(null=True)),
            ],
        ),
    ]
