# Generated by Django 3.1.6 on 2021-02-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassdoorreview',
            name='companyUrl',
            field=models.TextField(null=True),
        ),
    ]
