# Generated by Django 3.1.6 on 2021-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassdoor', '0003_glassdoorcompanies'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassdoorreview',
            name='employeesRatings',
            field=models.TextField(null=True),
        ),
    ]
